### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by Sandertv** [df-mc/dragonfly#133]
The README has out of date information on it and doesn't look very appealing to new visitors. It should probably also have the "Chat on Discord" button higher up so people see the button more quickly.

**Comment by ImDaRealAni** [comment]
I might be able to help with this a little.

Just wondering, have you considered using something such as GitBook for documentation?

**Comment by Sandertv** [comment]
I can't say I have. Right now we just use the Wiki for more global documentation, but GitBook might be interesting to have a look at! The biggest (and only, really) pro from the GitHub Wikis is that everything is in one place.
