### ISSUE TITLE
Add a method to strike lightning in the world

### ISSUE THREAD

**Issue by Sandertv** [df-mc/dragonfly#134]
Lightning has traditionally been an entity, but it would probably be better if there was a simple method to strike lightning in a world. Something like `(*world.World).StrikeLightning(pos)` might work.

**Comment by T14Raptor** [comment]
Pushing this back.

**Comment by Sandertv** [comment]
Postponing to v0.3.0.

**Comment by Sandertv** [comment]
Random thoughts: Making this an entity might be easier after all. It needs to have access to specific blocks (fire) and needs to damage and set on fire entities around it. This would come with quite some hacks if added to the `world` package.
