### ISSUE TITLE
Quality of life fixes for commands

### ISSUE THREAD

**Issue by T14Raptor** [df-mc/dragonfly#171]
Having one command usage with an optional argument and one without that argument will always cause one of the two to be executed. What should happen here? Make sure to document whatever behavior we decide on.

- [x] Retain values of unexported fields.
- [ ] Reject commands in the above case.

**Comment by Sandertv** [comment]
Not exactly sure about the scope of this issue and what we'll have to do precisely. I'll be postponing this to v0.4.0 and probably after we implement realtime command updates.

**Comment by Thunder33345** [comment]
leaving a note as it was something that should have been part of this issue:

allowing unexported fields carry values rather then having to depend on a package variable

**Comment by Sandertv** [comment]
Postponing this to v0.5.0.
