### ISSUE TITLE
Cleaner main file

### ISSUE THREAD

**Issue by Restart-Dev** [df-mc/dragonfly#177]
Hi, I feel like these functions should just be checked in the srv.Start() function, it would make the main file look less all over the place. I know I could just add this check into another function but I think it should be in the srv.Start() function by default.
![image](https://user-images.githubusercontent.com/45609733/123033774-4c260200-d3b6-11eb-8be7-67bfb0b5ae6c.png)

**Comment by Sandertv** [comment]
Hi! Thanks for opening an issue!

I'm inclined to agree with this and I do think it's better we move this into server.go. I don't think there's any situation where having this message be harmful.
