### ISSUE TITLE
Implement projectiles

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#184]
There's no projectile on DF for the moment and.. for servers like mine where pvp is based on splashing potions we're kind of stuck and can't really release my server.

**Comment by Sandertv** [comment]
I can imagine this is an issue. I don't personally have a lot of time until next month, but if anyone wants to make a start on this so we can get this in the v0.2.0 release quickly, please don't hesitate.

**Comment by T14Raptor** [comment]
I'm going to work on this.

**Comment by Sandertv** [comment]
Postponing this to v0.3.0 too.

**Comment by Sandertv** [comment]
Raytracing was finished in v0.3.0 but unfortunately projectiles weren't yet. This is however being worked on actively and I imagine this'll be finished near the start of this month. Postponing to v0.4.0.

**Comment by Lucaskyy** [comment]
@Sandertv This has been implemented, right? Or was it #275 that implements this?

**Comment by Sandertv** [comment]
#275 implements this.

**Comment by Lucaskyy** [comment]
Alright 👍 Might want to link that PR to this issue then, if you want to.
