### ISSUE TITLE
Problem with player transfer.

### ISSUE THREAD

**Issue by Restart-Dev** [df-mc/dragonfly#185]
edit: the code I used: 
![image](https://user-images.githubusercontent.com/45609733/123170616-b8514600-d448-11eb-96c3-789017031706.png)

Hi, I found an issue with the player transfer function.
![image](https://user-images.githubusercontent.com/45609733/123170362-70caba00-d448-11eb-9dec-00e9ba4022ee.png)

What I expect is: the player get transferred to the server I want (which in this case is nozzle.wtf:19132)

What actually happened: The transfer function closes player's session which disconnects the player with the message: 
![image](https://user-images.githubusercontent.com/45609733/123170391-7a542200-d448-11eb-9b2f-02955682f33a.png)

I tried removing the close function and everything was working! so I think we should either remove this function in the transfer or just find another way to close the session of the player without preventing the player from being transferred

**Comment by Sandertv** [comment]
I think updating the gophertunnel version in the go.mod to v1.13.1 should fix this.

**Comment by Restart-Dev** [comment]
It did not fix the problem for me

**Comment by Restart-Dev** [comment]
> 
> 
> I think updating the gophertunnel version in the go.mod to v1.13.1 should fix this.

It did not fix the problem for me

**Comment by Sandertv** [comment]
If that is the case I think we need to delay closing the player. I don't think there's a way around it.
