### ISSUE TITLE
Varargs error

### ISSUE THREAD

**Issue by Restart-Dev** [df-mc/dragonfly#196]
Hi, I found a little issue with Varargs, here's the whole error:

![image](https://user-images.githubusercontent.com/45609733/123875159-2ee9ba00-d907-11eb-9c2e-89e4e2aae1f9.png)

And here's my command:

![image](https://user-images.githubusercontent.com/45609733/123875200-3e690300-d907-11eb-9ec0-c8b6d3dc5a99.png)

**Comment by Sandertv** [comment]
Closed in d742cfc8c37c0e340e40f6d437c9231ff4d04226.
