### ISSUE TITLE
player.Player.Inventory().SetItem() on server.Server.Accept()

### ISSUE THREAD

**Issue by Endermanbugzjfc** [df-mc/dragonfly#200]
# Error

```
DEBU[0092] failed processing packet from 
x.x.x.x:55750 (Endermanbugzjfc): *packet.InventoryTransaction: unhandled inventory transaction type *protocol.MismatchTransactionData
```
- Expected result: Item got set and inventory is synchronous between server and client
- Actual result: The error **sometimes** occur, depending on the network, delay of code execution, and of course luck

# Reproduce
Run `player.Player.Inventory().SetItem()` right after `server.Server.Accept()`

# Environment
- DragonFly: 0.1.0 4b13a4f305dfb7b9f9b6109955ba81f816844267
- OS: macOS Big Sur (Intel) version 11.4
- Network: Shitty school WiFi
- Go: 1.16
- Client: 1.17.2

**Comment by Sandertv** [comment]
Solution should be as simple as to just ignore mismatch transactions.

**Comment by Endermanbugzjfc** [comment]
> Solution should be as simple as to just ignore mismatch transactions.

How tho? It keeps kicking the client, forgot to mention this.

**Comment by Sandertv** [comment]
By not kicking :p

**Comment by Endermanbugzjfc** [comment]
> By not kicking :p

How?

**Comment by Sandertv** [comment]
By... not kicking, in Dragonfly. Note that this is marked a bug. It's not something on your end.
