### ISSUE TITLE
Some items are sometimes incorrect in the inventory

### ISSUE THREAD

**Issue by Sandertv** [df-mc/dragonfly#217]
Sometimes, some of the items displayed in the (creative) inventory are incorrect. In such cases, honeycombs are displayed as a bottle of honey, warped fungus on a sticks are displayed as chains. (Potentially more of such items.)

This was reproduced both by me and @DaPigGuy. It seems to fix itself automatically when leaving and joining again. Maybe something wrong with the item runtime IDs. I am not sure what could be the cause of this. Item runtime IDs are consistent for as long as the server is running (and technically even afterwards). Multiple players can experience and not experience the bug simultaneously.

**Comment by JustTalDevelops** [comment]
Could it be the order of the item runtime IDs? (unlikely, but worth a try?)

**Comment by Sandertv** [comment]
That possibility does exist yeah. We can try sorting them.

**Comment by Sandertv** [comment]
1f27b4a0177d77622e2937d6b951b43a5fbc464a does not fix the issue. To add to the list, when this bug happens, amethyst shards show up as spyglasses.

**Comment by Sandertv** [comment]
Sorting the items does not fix it. This seems to reliably reproduce everytime you join the server for the first time after you restart the game (on Android). Rejoining afterwards immediately fixes it.

**Comment by Sandertv** [comment]
It seems that joining a different server first before joining Dragonfly also prevents the issue from happening.

**Comment by Sandertv** [comment]
This seems very likely to just be a client issue, where the client expects we send all items in the StartGame packet while we only send items we implement.
