### ISSUE TITLE
Item throwing doesn't work when not held

### ISSUE THREAD

**Issue by Sandertv** [df-mc/dragonfly#219]
When throwing an item out of the hotbar on mobile editions, you do not actually need to select the item in the hotbar. Dragonfly assumes this has to be done however, and rejects item dropping if the item dropped is not held in the hand. This is incorrect behaviour.

**Comment by Sandertv** [comment]
This has not yet been fixed by the commit mentioned above. This is difficult to fix if we don't fully handle inventory transactions (which we don't). As this issue is of very low significance, I'm going to give this the v? milestone. If Mojang ever finished their changes to the inventory system, this should be fixed automatically.

**Comment by JustTalDevelops** [comment]
https://github.com/pmmp/PocketMine-MP/blob/minor-next/src/network/mcpe/handler/InGamePacketHandler.php#L389-L409

This might be of use.
