### ISSUE TITLE
Not being able to see other people sometimes in different worlds

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#237]

**Comment by Sandertv** [comment]
Could you give me, as far as you can, the exact minimal steps to reproduce this?

**Comment by Sandertv** [comment]
This might be a fairly serious issue but due to a lack of exact minimal reproduction steps I'll be postponing this to v0.4.0. If you have the time to get back to me about this, please do.

**Comment by JustTalDevelops** [comment]
I've really only had this happen mainly with multiple worlds (e.g. using the Emperials world manager).

As an example, say we have two players: player A and player B.

Player A joins the server, then switches to a different world. Then, player B joins the server, and then joins the world that Player A is now on. When Player B spawns in, he'll see Player A, but Player A won't see him.

**Comment by JustTalDevelops** [comment]
However, I don't believe this is necessarily the issue: when a player is added to a new world, they keep their original location. My original location in the first world is around 0 X and 0 Z. However, my actual build in the other world is at around 1000 X and `1000 Z, and since adding entities to a new world makes them keep their original location, I teleport them to the correct position. However, I noticed that Teleport doesn't broadcast the player to the new viewers of the player's new position, so only players who previously have seen the entity will see them in the other world. (?)
