### ISSUE TITLE
Fast equipping armour breaks with a item stack request error after the first armour equipped

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#242]

**Comment by Sandertv** [comment]
Could you please give more info on exactly the error?

**Comment by JustTalDevelops** [comment]
It seems to update fine in your inventory, but when you go to take it off, the server doesn't let you and errors this in the debug log:
`DEBU[0014] failed processing packet from [::1]:59894 (JustTalz): ItemStackRequest: error resolving item stack request: *protocol.TakeStackRequestAction: source slot out of sync: slot pointed to stack request -424, but request could not be found`

**Comment by JustTalDevelops** [comment]
Other players can also see the updated armour, so it's not client side.
