### ISSUE TITLE
Make the flat generator set the biome IDs in newly generated chunks to plains

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#277]
Right now, the flat generator does not modify the biome IDs, therefore keeping them at zero, which is the ID for the taiga biome. In vanilla Minecraft, flat generators always use one, or plains, for the biome IDs, which is why I believe it would make more sense to add an extra line to the flat generator to set the biome ID to one. This really shouldn't be too difficult of a task, and it'll also bring a little more consistency to DF with vanilla.

**Comment by Sandertv** [comment]
I feel this is somewhat pointless while we don't have a biome implementation. I think we should have an implementation for that if we do this.

**Comment by Sandertv** [comment]
This has been resolved in the biomes implementation.
