### ISSUE TITLE
setNameTag weird?

### ISSUE THREAD

**Issue by ZStarMCZ5487** [df-mc/dragonfly#278]
idk this is a bug or feature , but i think this should be fix 
i set my name to EEE, but the chat still show my own name

(i had namdtag on head mod enable*)
![Screenshot 2021-09-15 162322](https://user-images.githubusercontent.com/73019806/133399099-b83e1f9b-5aa1-4978-80dc-283726c5d569.png)

**Comment by provsalt** [comment]
This is intentional according to the documentation
https://pkg.go.dev/github.com/df-mc/dragonfly/server/player#Player.SetNameTag

**Comment by Endermanbugzjfc** [comment]
@ZStarMCZ5487 This happens in both PocketMine-MP and DragonFly. `SetNameTag()` only changes the name tag on top of the player's head. To change the name in PocketMine-MP, you have to the listener for the player chat event and modify its parameters. The way in DragonFly should be similar.
