### ISSUE TITLE
Add player.SetHealth

### ISSUE THREAD

**Issue by Mohamed587100** [df-mc/dragonfly#284]

**Comment by Lucaskyy** [comment]
player.Hurt exists.

**Comment by RestartFU** [comment]
> player.Hurt exists.

well I don't think that's what he wants. he wants to either add or remove health from the player depending on the health the player currently has and the health he wants the player to have

**Comment by Sandertv** [comment]
You can do that with the Hurt and Heal methods.

**Comment by Mohamed587100** [comment]
in some case, there need to set player's health directly, but if use Heal or Hurt, you have to caculate health delta and it isn't convenient at all.

**Comment by Sandertv** [comment]
The thing is that healing and hurting are simply different things. A SetHealth method breaks that difference and exposes health changing in an 'incomplete' way (can't listen for events) which is not very desirable.

**Comment by Lucaskyy** [comment]
I agree with you Sander, but you can maybe just have such method, then get the current player health and if the health argument is lower than the current player health Hurt them etc.. More of a utility method, so to say.

**Comment by Mohamed587100** [comment]
> I agree with you Sander, but you can maybe just have such method, then get the current player health and if the health argument is lower than the current player health Hurt them etc.. More of a utility method, so to say.



> I agree with you Sander, but you can maybe just have such method, then get the current player health and if the health argument is lower than the current player health Hurt them etc.. More of a utility method, so to say.

I support this as a balanced approach of SetHealth

**Comment by Lucaskyy** [comment]
There are some complexities with this that we discussed in the Discord server, which we need to figure out.

**Comment by Sandertv** [comment]
If there are no other comments on this I will close this and its associated PR.
