### ISSUE TITLE
Implement biomes (1.18)

### ISSUE THREAD

**Issue by Lucaskyy** [df-mc/dragonfly#326]

**Comment by Lucaskyy** [comment]
I'd like to take a look into this, if possible. Depends if this is isn't low priority though.

**Comment by Sandertv** [comment]
Please do feel free. One thing to keep in mind though, is that biomes are going to be 3-dimensional soon. With experimental gameplay this is already the case. This changes the dynamics of biomes quite a bit.

**Comment by Lucaskyy** [comment]
Ah okay, could you elaborate and/or link me to a resource that explains this a little more in-depth?

**Comment by Sandertv** [comment]
Not really because no such documentation exists. At some point when it leaves experimental gameplay we can implement it too though. As opposed to biomes being in columns, they will be per-block with a paletted format similar to blocks themselves.

**Comment by Sandertv** [comment]
The 3D biome storage has been done so we should be able to build some sort of API around that now.
