### ISSUE TITLE
Just crashes on join

### ISSUE THREAD

**Issue by PalmTamino** [df-mc/dragonfly#339]
C:\Users\tamino\Downloads\TheProject Bedrock>go run main.go
go: downloading github.com/pelletier/go-toml v1.9.3
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/sandertv/gophertunnel v1.17.1
go: downloading github.com/go-gl/mathgl v1.0.0
go: downloading github.com/google/uuid v1.3.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/df-mc/goleveldb v1.1.9
go: downloading github.com/brentp/intintmap v0.0.0-20190211203843-30dc0ade9af9
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1
go: downloading golang.org/x/image v0.0.0-20210628002857-a66eb6448b8d
go: downloading golang.org/x/net v0.0.0-20210716203947-853a461950ff
go: downloading github.com/sandertv/go-raknet v1.10.2
go: downloading golang.org/x/oauth2 v0.0.0-20210628180205-a41e5a781914
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading github.com/muhammadmuzzammil1998/jsonc v0.0.0-20201229145248-615b0916ca38
go: downloading github.com/klauspost/compress v1.13.6
go: downloading golang.org/x/crypto v0.0.0-20210711020723-a769d52b0f97
go: downloading github.com/golang/snappy v0.0.3
INFO[0000] Starting Minecraft Bedrock Edition server for v1.18.0...
DEBU[0000] Loading world...
DEBU[0000] Loaded world 'World'.
INFO[0000] Server running on [::]:19132.
FroschPferd05 has joined the game
panic: runtime error: index out of range [32737] with length 2048

goroutine 7 [running]:
github.com/df-mc/dragonfly/server/world/chunk.(*SubChunk).SkyLight(...)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/chunk/sub_chunk.go:90
github.com/df-mc/dragonfly/server/world/chunk.(*Chunk).Light(0xffffffff, 0x40, 0x14, 0xc0)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/chunk/chunk.go:79 +0xc6
github.com/df-mc/dragonfly/server/world.(*World).Light(0xc00014cb40, {0xffffffffffffffff, 0xffffffffffffffc2, 0xc})
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:601 +0xa5
github.com/df-mc/dragonfly/server/block.Grass.RandomTick({{}}, {0x0, 0xffffffffffffffc3, 0xb}, 0xc000c3a540, 0xc000124ae0)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/block/grass.go:73 +0x309
github.com/df-mc/dragonfly/server/world.(*World).tickRandomBlocks(0xc00014cb40, {0xc000345f30, 0x1, 0x9d5642500010000}, 0x0)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:1429 +0x3c2
github.com/df-mc/dragonfly/server/world.(*World).tick(0xc00014cb40)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:1230 +0x42c
github.com/df-mc/dragonfly/server/world.(*World).startTicking(0xc00014cb40)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:1154 +0xac
created by github.com/df-mc/dragonfly/server/world.New
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:95 +0x41d
exit status 2

C:\Users\tamino\Downloads\TheProject Bedrock>go run main.go
INFO[0000] Starting Minecraft Bedrock Edition server for v1.18.0...
DEBU[0000] Loading world...
DEBU[0000] Loaded world 'World'.
INFO[0000] Server running on [::]:19132.
FroschPferd05 has joined the game
panic: runtime error: index out of range [4074] with length 2048

goroutine 11 [running]:
github.com/df-mc/dragonfly/server/world/chunk.(*SubChunk).SkyLight(...)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/chunk/sub_chunk.go:90
github.com/df-mc/dragonfly/server/world/chunk.(*Chunk).Light(0xffffffff00000001, 0x40, 0x14, 0xc0)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/chunk/chunk.go:79 +0xc6
github.com/df-mc/dragonfly/server/world.(*World).Light(0xc00014ab40, {0x1d, 0xffffffffffffffc4, 0xfffffffffffffff5})
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:601 +0xa5
github.com/df-mc/dragonfly/server/block.Grass.RandomTick({{}}, {0x1d, 0xffffffffffffffc3, 0xfffffffffffffff5}, 0xc0005316b0, 0xc0002fab10)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/block/grass.go:48 +0xbd
github.com/df-mc/dragonfly/server/world.(*World).tickRandomBlocks(0xc00014ab40, {0xc0003f8340, 0x1, 0x853fc11b00010000}, 0x0)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:1429 +0x3c2
github.com/df-mc/dragonfly/server/world.(*World).tick(0xc00014ab40)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:1230 +0x42c
github.com/df-mc/dragonfly/server/world.(*World).startTicking(0xc00014ab40)
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:1154 +0xac
created by github.com/df-mc/dragonfly/server/world.New
        C:/Users/tamino/Downloads/TheProject Bedrock/server/world/world.go:95 +0x41d
exit status 2

C:\Users\tamino\Downloads\TheProject Bedrock>

**Comment by Sandertv** [comment]
Thanks for the report! It's fixed in the latest commit.

**Comment by PalmTamino** [comment]
> Thanks for the report! It's fixed in the latest commit.

Hello, is it possible for me to try that version with that commit?

**Comment by PalmTamino** [comment]
Oh, it is already fixed in the code, did not saw that. Sry i am a noob in github.
