### ISSUE TITLE
Rejoining a server crashes the client

### ISSUE THREAD

**Issue by AndreasHGK** [df-mc/dragonfly#341]
Whenever I join my df server, and then disconnect and rejoin my client will crash after a few seconds.
This does not seem to happen if I first restart the server before rejoining.

mc: v1.18.0.2 windows 10 edition
df version: commit 355b5b4aa373a4f853d967d675f91bef438ee57c

**Comment by Sandertv** [comment]
I don't seem to be able to reproduce on my phone. Could you try joining the development server and see if it happens there too?

**Comment by Sandertv** [comment]
Seems to be happening inconsistently. Unclear what influences this. Hasn't been reproduced on non-local servers yet.

**Comment by Sandertv** [comment]
d8b68388e4bf4e593c9eeaed1803c547ef4292fb might have fixed this(?)

Could you please report if this issue happens again at any point?

**Comment by AndreasHGK** [comment]
It didn't fix it
I just realized it seems to be happening after I open chat and type / (to type a command ofc)

**Comment by Sandertv** [comment]
Hahahah I know what that issue is. That makes it a lot clearer.

**Comment by AndreasHGK** [comment]
yea sorry i didnt realize it always happened when trying to execute a command 😅
