### ISSUE TITLE
Handle the sound (HandlePlaySound and HandleViewSound)?

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#347]
so, I think being able to handle the sound can be useful for many, including me. I think that we should have one handler for sounds that were played using the PlaySound function in the *Player. <- pretty easy, yes. But being able to handle the sounds that were played through ViewSound, the player being a Viewer, is something that I've been looking into, and I didn't find anything that wouldn't make some big changes to dragonfly, which is why I didn't PR anything.

**Comment by Sandertv** [comment]
I propose we add a `HandleSound` in `world.Handler`. The `(*player.Player).PlaySound()` method is not called by dragonfly itself, so having a handler for that doesn't sound very useful.
