### ISSUE TITLE
Implement a system for different dimensions

### ISSUE THREAD

**Issue by Sandertv** [df-mc/dragonfly#348]
There is a need for worlds with different dimensions that aren't just the overworld. We have discussed some ideas in Discord and we figured the following is the most reasonable and attainable.

There are a couple of requirements for the implementation:
- We don't want to introduce another layer of complexity by making a `World` a container of multiple `Dimension`s.
- We want to be able to maintain vanilla compatibility, meaning different dimensions should be able to share the same leveldb database.
- Worlds (created by the user) must allow setting the nether and end portal destination world.

The current idea is the following:
- Have `(*server.Server).Nether() *world.World` and `(*server.Server).End() *world.World` methods.
- Have both of these worlds share the same underlying leveldb database to maintain full compatibility with Bedrock Edition worlds.
- Add `(*world.World).NetherPortalDestination(*world.World)` and `(*world.World).EndPortalDestination(*world.World)` methods to allow settings the destination worlds for portals in a specific world.
- Add a new `type world.Dimension interface{ EncodeDimension() uint32; Range() [2]int }` with implementations for the Overworld, Nether and End. 
- Accept a `world.Dimension` in `world.New()` to specify the dimension of a World upon creation. We should also add a `(*world.World).Dimension() world.Dimension` method.
- Change all code to rely on the `(world.Dimension).Range()` method for the world height (and depth). Different dimensions have different ranges client-side, so we must and should support this server-side too.

Current issues with the above we haven't worked out yet:
- When an overworld, nether and end world share the same underlying leveldb database, their `world.Settings` must be synchronised because all dimensions share the same time, world name, game rules etc. If we have `world.Provider` return a `*world.Settings` instead with a `sync.Mutex` in there, the synchronisation aspect is solved. The only problem then is that each of the dimensions will, for example, advance the time and weather, while this should only happen once. I am not sure how we should solve this.

**Comment by AndreasHGK** [comment]
Should the dimension interface also contain `AllowsWater() bool` and `FastLava() bool` interfaces?

**Comment by Sandertv** [comment]
Yep, probably so.

**Comment by Sandertv** [comment]
Most of the points above are taken care of on the feature/dimensions branch, except for the synchronisation of the `*world.Settings`. I haven't fully decided on how to approach that yet.
