### ISSUE TITLE
Drinking a potion that kills you makes you respawn with a glass bottle

### ISSUE THREAD

**Issue by Sandertv** [df-mc/dragonfly#351]
When drinking a harming potion that ends up killing you, the resulting glass bottle ends up staying in your inventory when you die to it.

**Comment by T14Raptor** [comment]
Would it be better to add a dead check in `(*Player).addNewItem` or clear inventories again in `(*Player).Respawn`? Or both? Or would these solutions be more of a workaround rather than fixing the actual problem?

**Comment by Sandertv** [comment]
The latter would not work as the item wouldn't be dropped properly on death. Adding a check in addNewItem might work.
