### ISSUE TITLE
Implement to the inventory or player handler a method to handle when a player put on / remove armour

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#352]

**Comment by Sandertv** [comment]
You should already be able to do this by adding an inventory.Handler to Player.Armour(). Could you try that?

**Comment by RestartFU** [comment]
> You should already be able to do this by adding an inventory.Handler to Player.Armour(). Could you try that?

*Player.Armour() only returns an ArmourContainer which does not implement *Inventory

**Comment by Sandertv** [comment]
You can call Player.Armour()
Inv().
