### ISSUE TITLE
the HandleTake or HandlePlace, in the inventory Handler does not seem to be taking in count when the item is at the armour slot, which is annoying. I also think that we should have a handler for the armour, and not only the inventory

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#353]

**Comment by Sandertv** [comment]
I am not sure what you mean. Could you elaborate or send a video if that makes it more clear?

Why is a handler for the inventory not sufficient? I'm not really a fan of adding two methods for the same thing.
