### ISSUE TITLE
HandleQuit() sometimes gets called multiple times

### ISSUE THREAD

**Issue by AndreasHGK** [df-mc/dragonfly#359]
For a while I've been having some problems with HandleQuit, so I added a `fmt.Println("Handling quit for", s.Player().Name())`, and as I suspected I got the following output:
```
INFO[0057] Server shutting down...
DEBU[0057] Disconnecting players...
Handling quit for AndreasHGK
Handling quit for AndreasHGK
panic: player AndreasHGK does not yet have a session
```
I dont think my code has anything to do with it tho, as I've experienced errors when handling quit on completely different projects before but was never able to find the bug (until now). I think this bug has existed for multiple months
Most of the time the event works correctly, but other times it seems to call HandleQuit() twice. I'm not exactly sure when it happens.

The last time it happened it was when i used crtl+c to close the server. This also doesn't seem to 100% reliably cause it to happen tho, in fact usually it doesnt happen so I am clueless as to why or when exactly it happens.

**Comment by AndreasHGK** [comment]
ps: the session error is my code and has nothing to do with the dragonfly session package

**Comment by T14Raptor** [comment]
Could you test this with plain dragonfly handlers? The only time `HandleQuit` is called, the player's handler is set to a `NopHandler`, so even if it's being called twice, it shouldn't be able to get handled twice.

https://github.com/df-mc/dragonfly/blob/master/server/player/player.go#L2212-L2214
```
p.handler().HandleQuit()

p.Handle(NopHandler{})
```

**Comment by AndreasHGK** [comment]
I don't seem to be able to reproduce it with a plain handler oddly enough, but im not really sure when it happens in the first place

**Comment by T14Raptor** [comment]
Could it be a problem with your original code?

**Comment by Sandertv** [comment]
Note that the above commit makes it impossible for this issue to happen if its cause is within Dragonfly. If it does still happen (I suspect it might, this race condition seems highly unlikely), you might want to check your code.
