### ISSUE TITLE
adding code into the HandleSkinChange() {} will make code in srv.Accept dont work somehow,i not sure it is a bug or not

### ISSUE THREAD

**Issue by ZStarMCZ5487** [df-mc/dragonfly#361]
trying to disable these player who use weird model skin in server (i saw ppl use ender dragon model skin in server before,and its annoying)

**Comment by T14Raptor** [comment]
Could you add the code to the issue?

**Comment by ZStarMCZ5487** [comment]
const (
                CustomSlimGeometry = "geometry.humanoid.customSlim"
        )
        skin1 := p.Skin()
	sPix := skin1.Pix
	s := skin.New(skin1.Bounds().Max.X, skin1.Bounds().Max.Y)
	s.Pix = sPix
	s.Persona = false
	s.ModelConfig = skin.ModelConfig{Default: CustomSlimGeometry}

**Comment by T14Raptor** [comment]
All of it?

**Comment by ZStarMCZ5487** [comment]
oh btw i put p.SetSkin() inside the HandleSkinChange 
i was trying to make that if player use weird model skin , then it will turn it to CustomSlimGeometry

**Comment by ZStarMCZ5487** [comment]
nvm its fixed
