### ISSUE TITLE
be able to set scoreboard lines even if out of bounds (in case you care about the order and your scoreboard is dynamic)

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#367]
changing the lines from []string to a map[int]string would make this possible

imo, this is something that we should be able to do, set a line even if it's not following the order 1, 2, 3, 4.
I sometimes will remove some lines and, when I want to add them back, I want to keep a logical order, I want this kind of content to always be at that line.

**Comment by Sandertv** [comment]
I don't fully see the need for this. Sounds like there are plenty of other ways to approach this? Like having different scoreboard values when their general structure is different?

**Comment by RestartFU** [comment]
> I don't fully see the need for this. Sounds like there are plenty of other ways to approach this? Like having different scoreboard values when their general structure is different?

I'll give you an example here:
I have a pearl cooldown a Spawn Tag 
and Archer tag.

Let's say I always want my spawn tag to be on top, when the player is no longer in spawn tag, I remove it. But I still want it to be on top, but what if there's already two things at 1 and 2? I would have to do checks to then move those down just to put that one on top.

I hope you understand
