### ISSUE TITLE
Cannot break Dragon Egg in creative

### ISSUE THREAD

**Issue by RoyalMCPE** [df-mc/dragonfly#391]
Attempting to break the Dragon Egg in creative will cause it to teleport instead of breaking. 

Minecraft Version: 1.18.2
OS: LinuxMint 20.1
Go Version: 1.17.3 linux/amd64
DF Version: ba7d3845ae612bd0449c27e357a23657f087ec3d

**Comment by T14Raptor** [comment]
Fixed by 8ee5e6f42600d9916714f254110e413c929b4dae.
