### ISSUE TITLE
Example Plugin Repo 

### ISSUE THREAD

**Issue by PocketMiner92** [df-mc/dragonfly#400]
Hello Dragonfly Team.
Can you add a Example Plugin for it?
This would be Nice.

**Comment by AndreasHGK** [comment]
Dragonfly doesnt support plugins lile the ones you may be familiar with from other server softwares. Instead, dragonfly is meant to be used as a library for you to make your server with. An example can be found in the df-mc/plots repo, it is a basic plots server made using df.

**Comment by mmm545** [comment]
dragonfly doesn't have plugins, it's more like a library that has to be included by another program, here is a template https://github.com/df-mc/template

**Comment by Sandertv** [comment]
If you need anymore information, you could also have a look at the Wiki. The difference between Dragonfly and something like PocketMine is explained there. Feel free to let us know if you have any other questions in the Discord.

**Comment by PocketMiner92** [comment]
Great, i think this much better.
I was long years Pocketmine User but now its a blame and i looking for a better one.
Is there any Testserver for Dragonfly?

**Comment by AndreasHGK** [comment]
> Great, i think this much better. I was long years Pocketmine User but now its a blame and i looking for a better one. Is there any Testserver for Dragonfly?

sorry for the late reply, if you're still interested this should be the ip for a plain df testserver 188.166.78.44:19132

**Comment by PocketMiner92** [comment]
Thank you very much.

**Comment by PocketMiner92** [comment]
Wow
New Items are implemented.
Its great.
Nice Job.
