### ISSUE TITLE
SubCommands dont work

### ISSUE THREAD

**Issue by Prim69** [df-mc/dragonfly#410]
here is the code used
```go
cmd.Register(cmd.New("time", "§bChange the time of the world you're in.", nil, TimeSet{}))

type TimeSet struct {
	Time int
}

func (TimeSet) SubName() string {
	return "set"
}
```
cmd.Usage() returns `/time <Time: int>`
![image](https://user-images.githubusercontent.com/13991048/150621546-adb67624-3846-485d-b42c-ebf93e9cbb27.png)

**Comment by Sandertv** [comment]
This isn't the way to implement subcommands. Have a look at the plots subcommand like here: https://github.com/df-mc/plots/blob/master/plot/command/auto.go#L13.

**Comment by Prim69** [comment]
Oh thank you
