### ISSUE TITLE
Armour durability reset when take off armour

### ISSUE THREAD

**Issue by ZStarMCZ5487** [df-mc/dragonfly#416]

**Comment by ItsZodiaX** [comment]
https://youtu.be/PBsNgl2yoJA
It isn't actually reset, They all have the same durability but it doesn't show.

**Comment by Sandertv** [comment]
Related to https://github.com/df-mc/dragonfly/issues/313.

**Comment by Sandertv** [comment]
Could you try f595b52b92ea00fdc316d53459698b68ff734df2 and see if the issue persists?

**Comment by Sandertv** [comment]
Resolved by f2a81fe8adf7976ad13af5248048dbb5a83e6dec.
