### ISSUE TITLE
rotation issue when using a pearl (on landing)

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#423]
here is a little recording
https://youtu.be/6c2aZ_ClY2s
![image](https://user-images.githubusercontent.com/45609733/154572308-89c7de8c-c154-49a5-b9b7-fe95acc5b3b9.png)
here is also a screenshot from the discord in case sander isn't the one who's gonna focus on this issue

and here is also my pearl entity: https://pastebin.com/iDbYJatY

**Comment by RestartFU** [comment]
never mind, I was wrong. It still happens even without my proxy

**Comment by T14Raptor** [comment]
The problem is latency, the server sends the client an old yaw/pitch after the client has moved but the movement hasn't yet reached the server, causing the client's yaw/pitch to pretty much get rolled back.

**Comment by T14Raptor** [comment]
I believe the only solution would be to actually implement the server authoritative movement system (making use of the tick fields in packets etc.), basically #375.
