### ISSUE TITLE
issue when teleporting to new world and hitting right away

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#425]
![image](https://user-images.githubusercontent.com/45609733/154785674-698f1595-3436-4b72-a9b1-1f7981dd3b7e.png)
it makes ToutEnGucci Disconnect
here is how it happens: https://youtu.be/7-GmInsbgd4

**Comment by Sandertv** [comment]
Just to be clear, ToutEnGucci is not attacking you here, is that correct?

**Comment by RestartFU** [comment]
> Just to be clear, ToutEnGucci is not attacking you here, is that correct?

that is correct
