### ISSUE TITLE
Items still appear in hotbar after breaking

### ISSUE THREAD

**Issue by T14Raptor** [df-mc/dragonfly#432]
![image](https://user-images.githubusercontent.com/45741122/155141932-8bd87c7e-5700-49a5-a02a-b5f6fbec7f03.png)
![image](https://user-images.githubusercontent.com/45741122/155141942-45d05f04-0355-443c-bde4-1ef3ff81807d.png)

Might be related to
![image](https://user-images.githubusercontent.com/45741122/155141963-3231a031-9818-43a0-9ba9-2b0348467f57.png)

**Comment by Sandertv** [comment]
Fixed in 6230e728cc97bcae63bfdc022ad58b5d3db20763.
