### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference with worlds (not sure how it happens I was not online or anything)

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#435]
this seems to have happened after someone died, I don't know if it was right after they died because I was not online.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58cbc4]

goroutine 27 [running]:
github.com/df-mc/dragonfly/server/world.(*World).tickEntities(0xc000b48a00, 0x2)
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220224010639-e5d56286b14a/server/world/world.go:1613 +0x4a4
github.com/df-mc/dragonfly/server/world.(*World).tick(0xc000b48a00)
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220224010639-e5d56286b14a/server/world/world.go:1357 +0x5c6
github.com/df-mc/dragonfly/server/world.(*World).startTicking(0xc000b48a00)
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220224010639-e5d56286b14a/server/world/world.go:1276 +0xac
created by github.com/df-mc/dragonfly/server/world.New
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220224010639-e5d56286b14a/server/world/world.go:109 +0x47b
exit status 2

**Comment by Sandertv** [comment]
It seems this is happening when a player is teleported/removed from the world/closed at a time right before the chunk cache janitor kicks in and unloads that chunk.

The crash happens on this line: https://github.com/df-mc/dragonfly/blob/e5d56286b14a28266745c301132ae3b5a42b9c70/server/world/world.go#L1612, which seems like it would happen in the above case, where an entity is moved from its chunk and the chunk no longer loaded.
