### ISSUE TITLE
can't send messages while being in gamemode 3 (spectator)

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#439]
![image](https://user-images.githubusercontent.com/45609733/156694034-2ca587d2-daa4-454c-8245-f60281c38021.png)
so, we cannot send messages while being in spectator mode, I don't know if it is supposed to be that way.

**Comment by Sandertv** [comment]
Resolved in 9d9e3aec49554e4c8ac6f1e1637615d9c5064584.
