### ISSUE TITLE
Have to fly in creative mode, then switch to spectator mode to be able to sprint in spectator mode

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#440]
here is a recording showing it
https://youtu.be/3UQDOIGGUXE

**Comment by Sandertv** [comment]
Should be fixed in b2f8662cc97dfe01f5ab07c00bb10d0eb37313ca, could you please let me know if that resolves your issue?

**Comment by RestartFU** [comment]
it seems to be fixed. Thanks
