### ISSUE TITLE
weird sprint issue when sneaking while sprinting in gamemodes where you can fly

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#442]
https://www.youtube.com/watch?v=gYT1HLxeDQw

**Comment by RestartFU** [comment]
this seems to still happen in spectator mode, you can fix it by acting as if you were in creative mode, press space twice (do that process twice) It looks like it does not set you as if you are flying when you get in spectator mode.

**Comment by Sandertv** [comment]
Please open a new issue for this, I think that is a different issue.
