### ISSUE TITLE
Stored player direction is wrong

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#452]
You can test this by joining, facing a direction, and then rejoining. Your player will be facing a different direction.

**Comment by Sandertv** [comment]
@JustTalDevelops are you able to debug if this is because of an error in the data saving/loading or just the client itself being weird?

**Comment by JustTalDevelops** [comment]
I am pretty positive this is an issue with Dragonfly - using a custom provider and setting a direction seems to work fine consistently.

**Comment by Sandertv** [comment]
That is weird. I just can't seem to find anything wrong with the way yaw/pitch is loaded or stored 🤔

**Comment by T14Raptor** [comment]
Is the different direction consistent?

**Comment by Sandertv** [comment]
@JustTalDevelops ^

**Comment by JustTalDevelops** [comment]
What exactly do you mean by that?

**Comment by Sandertv** [comment]
I'm unable to reproduce this. Could you make sure this happens with a vanilla dragonfly server?

**Comment by unickorn** [comment]
I also cannot reproduce this, maybe close it at this point unless Tal has something to add?

**Comment by JustTalDevelops** [comment]
No, this still seems to be happening. Just tested on latest commit.

**Comment by Sandertv** [comment]
This appears to be fixed since entity transactions.
