### ISSUE TITLE
Make Enchanting possible over MaxLevel.

### ISSUE THREAD

**Issue by DidntPot** [df-mc/dragonfly#461]

**Comment by JustTalDevelops** [comment]
I'm pretty positive this was fixed in one of the newer commits - are you on the latest?

**Comment by DidntPot** [comment]
> I'm pretty positive this was fixed in one of the newer commits - are you on the latest?

Oh really?

**Comment by DidntPot** [comment]
Nvm then. I thought it wasn't fixed.
