### ISSUE TITLE
World change crash

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#485]
If a player changes their world and doesn't move and gets attacked, their game will freeze up. This seems to only happen on Dragonfly.

**Comment by Sandertv** [comment]
Is this still reproducible these days? With a couple of Minecraft updates since and the dimension change packets we now send, I imagine this might have changed?

**Comment by JustTalDevelops** [comment]
This doesn't seem to be the case as of now, probably because of the dimension change packets, so I suppose we can mark this as resolved.
