### ISSUE TITLE
not being timed out after having an issue

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#492]
so, I was able to receive packets, I was seeing players move and chat updating, but it looked like the server wasn't handling my packets. The issue happened while I was just hanging around, walking in spawn (vasar). it's been about 45 minutes and It still shows that I am online. I also cannot reconnect.

**Comment by Sandertv** [comment]
Could you please try updating to 25af255957a8e898f21ed1b15f8292d321c19b1d and check if it still happens there?
