### ISSUE TITLE
Punching a floating text makes your item lose durability

### ISSUE THREAD

**Issue by Prim69** [df-mc/dragonfly#504]

**Comment by Sandertv** [comment]
Have you checked to see if this is a clientside issue by moving the tool around the inventory after it loses durability to a text entity?

**Comment by T14Raptor** [comment]
This appears to be client sided.

**Comment by JustTalDevelops** [comment]
> This appears to be client sided.

Is there any form of packet from the client to indicate that it hit a text? We could always just resend the item in hand to combat this, but if we don't get anything, I'm not sure when to do so.

**Comment by T14Raptor** [comment]
AttackEntity is called like normal

**Comment by JustTalDevelops** [comment]
I think we can probably just resend the held item in that case.

**Comment by T14Raptor** [comment]
Yeah that was the plan
