### ISSUE TITLE
panic when setting a block while using the dragonfly world api on gophertunnel as a virtual world.

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#514]
![image](https://user-images.githubusercontent.com/45609733/170146348-59779a3c-db4b-4c93-ba58-8878edce980b.png)
![image](https://user-images.githubusercontent.com/45609733/170146359-579752cc-1092-4acf-a8a1-a4f54fe48a27.png)

**Comment by Sandertv** [comment]
This seems to be an issue within your code, presumably where you call `world_setChunk()`. Make sure that the chunk you set is filled with light when you add it to the world using `chunk.NewLightArea(...).Fill()`.
