### ISSUE TITLE
proposal: Optional command parameter rework

### ISSUE THREAD

**Issue by AndreasHGK** [df-mc/dragonfly#515]
There is currently a limitation to how optional commands are done: you cant be sure whether a parameter was provided or that the user just gave the null value as an argument.

This is not unfixable, and I believe something similar to rust's Option<> type might be a way to solve this.
I have already implemented something like this in a library of my own: https://github.com/AndreasHGK/go-interactions and, while not the cleanest implementation, it does seem to work.

A command with an optional parameter would look like this:
```go
type MyCommand struct {
    RequiredParam string
    OptionalParam cmd.Optional[string]
}

func (m MyCommand) Run(...) {
    optionalString, ok := m.OptionalParam.Read()
    alsoOptionalString := m.OptionalParam.ReadOrDefault("this is a default string")
}
```

Even if this is implemented, the old way of doing commands could technically still be supported but I am not sure if that is such a good idea, and DF is in alpha anyway.

**Comment by Sandertv** [comment]
Closed in 92477ebb1dc8c355c08eef1421ae80670bd6295d.
