### ISSUE TITLE
Block placement rejected when close to target

### ISSUE THREAD

**Issue by ProtectorYT364** [df-mc/dragonfly#525]
When standing too close to a block while placing it the placed block disappear, tested in the latest df version

Video: https://streamable.com/hdzdo8
Video2: https://streamable.com/thcyem
Video3: https://streamable.com/45xnxd

**Comment by Sandertv** [comment]
Thanks for reporting! Could you try 4125eadb1d8a2112712b875d67da78a1a662b1bc and see if it fixes your issue?

**Comment by ProtectorYT364** [comment]
yea, now its fixed

**Comment by Sandertv** [comment]
Perfect, thanks!
