### ISSUE TITLE
Missing block aliases for stone slabs

### ISSUE THREAD

**Issue by ZStarMCZ5487** [df-mc/dragonfly#529]
i got this error while start the server
ERRO[0000] load chunk: failed loading (23, 21): cannot get runtime ID of block state minecraft:stone_slab{map[stone_slab_type:quartz top_slot_bit:0]}  dimension=overworld
and it does not even fixed when i load the world in vanilla then load it in df again

**Comment by ZStarMCZ5487** [comment]
and btw i also got this one as well
ERRO[0334] load chunk: failed loading (29, 15): cannot get runtime ID of block state minecraft:stone_slab{map[stone_slab_type:smooth_stone top_slot_bit:1]}  dimension=overworld

**Comment by AndreasHGK** [comment]
did you use a converter to convert this world? if so that is likely the cause

**Comment by ZStarMCZ5487** [comment]
yes, but everything work fine before i upgrade to newest df commit

**Comment by Sandertv** [comment]
Blame vanilla for this one, they renamed all the `stone_slab` states with `stone_block_slab`. I'm not sure what'll work if loading it in vanilla doesn't.

**Comment by JustTalDevelops** [comment]
They are now aliases, I just haven't had the time to update the mappings to support them. Will get to that before the v0.8.0 release.
