### ISSUE TITLE
Add support for 32-bit devices

### ISSUE THREAD

**Issue by TaskPro152** [df-mc/dragonfly#530]
Could yo
![IMG_20220614_102116](https://user-images.githubusercontent.com/97619080/173530944-222e8d8e-2ceb-49ec-9cd4-9e8d115a05b0.jpg)
![Uploading Screenshot_2022-06-14-10-21-01-784_com.termux.jpg…]()

u please add 32bit support as well?

**Comment by Flonja** [comment]
The error is not really clear, can you send this in text instead?

**Comment by AndreasHGK** [comment]
> The error is not really clear, can you send this in text instead?

it was sent in the discord, here it is
![image](https://user-images.githubusercontent.com/36563463/173571602-304a5051-b94e-4e95-8149-b0f5cf65b331.png)

**Comment by arfush** [comment]
If someone decides to add support for the 32-bit architecture, they will have to create a new branch (for dragonfly and gohertulele) or limit the 64-bit architecture.

So I don't think anyone will be doing this.

**Comment by Sandertv** [comment]
There is no need to limit anything. Go takes care of 99% of that, we just need to make sure atomic fields are aligned properly. This only takes a couple of minutes.

**Comment by Sandertv** [comment]
I think this has been fixed since switching to sync/atomic. If anyone finds this issue does still occur on 32 bit systems, please feel free to comment and I will reopen this issue.
