### ISSUE TITLE
Change `cmd.SubCommand` to a type that isn't an interface.

### ISSUE THREAD

**Issue by Sandertv** [df-mc/dragonfly#531]
Instead of requiring implementation of this interface, we could simply make `cmd.SubCommand` a type that isn't an interface and allow using that as a parameter type directly. We could then use the field name and `cmd:""` struct tag to let users specify the name of the subcommand. This means we wouldn't have to keep implementing new types for every subcommand.

**Comment by T14Raptor** [comment]
adc6278f91f6491daa5a38dbe7d814ac6cfb2887 resolves this right?

**Comment by Sandertv** [comment]
Yep, thanks for reminding!
