### ISSUE TITLE
entity's position still changing, even when returning before ticking movement in Tick()

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#534]
here is the Tick() code, I am setting lock to true when the entity hits something that isn't another entity:

```go
func (f *FishingHook) Tick(w *world.World, current int64) {
	if f.close {
		_ = f.Close()
		return
	}

	held, _ := f.owner.HeldItems()
	if r, ok := held.Item().(interface {
		Rod() bool
	}); !ok || !r.Rod() {
		f.close = true
		return
	}
	if f.lock {
		return
	}

	f.mu.Lock()
	vel := f.vel
	m, result := f.c.TickMovement(f, f.pos, vel, 0, 0, f.ignores)
	f.pos, f.vel = m.Position(), m.Velocity()

	f.age++
	f.mu.Unlock()

	m.Send()

	if result != nil {
		if res, ok := result.(trace.EntityResult); ok {
			if l, ok := res.Entity().(entity.Living); ok && !l.AttackImmune() {
				if _, vulnerable := l.Hurt(0.0, damage.SourceProjectile{Projectile: f, Owner: f.Owner()}); vulnerable {
					if p, ok := l.(*player.Player); ok {
						// Push back the target.
						p.KnockBack(l.Position().Sub(vel), 0.274, 0.372)
						if p.Sprinting() {
							p.StopSprinting()
							time.AfterFunc(time.Millisecond*100, func() {
								p.StartSprinting()
							})
						}
					}
				}
			}
			f.close = true
		} else {
			f.lock = true
		}
	}
} 
```
and here is a video showing it: https://youtu.be/776Z-EpTKGA

**Comment by Sandertv** [comment]
Could you do some debugging to see if that bool is actually changed?

**Comment by Sandertv** [comment]
Also could you verify that this is not a client-side thing by logging or otherwise showing the current position of the entity?

**Comment by RestartFU** [comment]
![image](https://user-images.githubusercontent.com/45609733/177377293-be85cb88-f533-46b1-aa3a-94f8dce03898.png)
the bool is changed, and the position isn't changed. So this seems to be client-sided, any way I could still avoid that behavior ?

**Comment by Sandertv** [comment]
Try giving it an `Immobile()` method and returning false there if `f.lock` is true. That should make it stop moving client-side. (Also make sure to resend the entity state when doing that).

**Comment by RestartFU** [comment]
> Try giving it an `Immobile()` method and returning false there if `f.lock` is true. That should make it stop moving client-side. (Also make sure to resend the entity state when doing that).

thanks, that worked!
