### ISSUE TITLE
HandleApplyEffect

### ISSUE THREAD

**Issue by Prim69** [df-mc/dragonfly#538]
This would allow users to easily modify an effect without creating a new custom one for little changes

Something like HandleApplyEffect(effect *effect.Effect) or HandleApplyEffect(effect effect.Effect, level *int, particlesHidden *bool, duration *time.Duration)

**Comment by Sandertv** [comment]
I have some reservations over this. Is this really a change that is necessary? Could you give an example where this can do something you wouldn't already be able to do differently?

**Comment by Sandertv** [comment]
Why isn't it possible to just create a new effect instance?

**Comment by Prim69** [comment]
That would have to be in every place we apply a speed effect, we could have a user.ApplySpeed function and always use that instead of player.AddEffect to apply speed but that feels wrong and might cause import cycles

**Comment by Sandertv** [comment]
As discussed in the Discord, we chose not to add this because a function as proposed (`user.ApplySpeed`) would solve this. Adding a handler for this method opens a can of worms where it is no longer clear if *all* methods need a handler or not.
