### ISSUE TITLE
Effect particles remain even after expiration until entity metadata updates

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#555]

**Comment by JustTalDevelops** [comment]
This seems to be because Tick doesn't update entity metadata when effects are removed:
https://github.com/df-mc/dragonfly/blob/7beb28f3c95348c64596b8d2290ebe607a8e2d12/server/entity/effect.go#L123

I suppose simply updating the state of the entity to all viewers `if len(toEnd) > 0` would work?

**Comment by Sandertv** [comment]
Sounds good to me.
