### ISSUE TITLE
FOV "bouncing" when using a potion of speed and toggling sprint

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#569]

**Comment by Sandertv** [comment]
More info? Maybe a video?

**Comment by JustTalDevelops** [comment]
Your FOV will increase as it does with speed, but when you start sprinting it'll go back down to match the sprinting FOV and then back up to match the speed FOV. This all happens very quickly but I can try to get a video of it in action.

I suspect it probably has to do with sending the sprinting state to the client itself, but am not sure.

**Comment by JustTalDevelops** [comment]
This is actually a vanilla bug that is (possibly) fixed on 1.19.20. Sorry!
