### ISSUE TITLE
Blocks can be waterlogged in flowing water

### ISSUE THREAD

**Issue by Flonja** [df-mc/dragonfly#577]
Water seems to flow through sign(s).
This is obviously not vanilla parity.

Tested on the dragonfly dev server (`188.166.78.44:19132`)
Clips:

https://user-images.githubusercontent.com/20887403/179751694-b52afec9-d4b5-4a40-a364-be209f9b6363.mp4

https://user-images.githubusercontent.com/20887403/179751688-04988e0f-6253-46f9-b1db-46ba1c9f818b.mp4

**Comment by JustTalDevelops** [comment]
As discussed on Discord, this seems to be the case with any waterloggable block placed in flowing water.  Dragonfly allows this behaviour, while Vanilla does not. This also explains the "ghost water" that you see in the video, and lava not being affected by this.

**Comment by Flonja** [comment]
Skulls also appear to have this problem

![ApplicationFrameHost_5DnPKdwLvN](https://user-images.githubusercontent.com/20887403/180618565-40f9a50c-7f08-4216-9b32-78d681369829.png)
