### ISSUE TITLE
Explosions pass through liquids

### ISSUE THREAD

**Issue by DaPigGuy** [df-mc/dragonfly#612]

**Comment by JustTalDevelops** [comment]
How did you test this? I cannot reproduce

**Comment by JustTalDevelops** [comment]
This is because liquids such as water and Bedrock don't have blast resistance - though we should probably have a special case for liquids, since waterlogging exists.

**Comment by JustTalDevelops** [comment]
Resolved by commit #9c073874846c61ca50bedcc1509ffec8a1e4e1f1.
