### ISSUE TITLE
Bows still fire after switching the held slot while holding

### ISSUE THREAD

**Issue by ItsZodiaX** [df-mc/dragonfly#676]
[vanilla vs df](https://cdn.discordapp.com/attachments/693104634814005301/1027093190790086696/2022-10-05_12-37-07_Trim.mp4)

**Comment by Blackjack200** [comment]
```session.InventoryTransactionHandler.handleReleaseItemTransaction``` should call special a hacked ```player.ReleaseItem``` which don't call
```go
i.Item().(item.Releasable).Release(p, p.useDuration(), ctx)
```

**Comment by Blackjack200** [comment]
i think the direct way to solve that is 

change
https://github.com/df-mc/dragonfly/blob/4113479b6b3cf29b571048dce1f7c60f13580dc8/server/session/player.go#L661
to something just like 
```go
p.usingItem.CAS(true, false)
```
in
https://github.com/df-mc/dragonfly/blob/4113479b6b3cf29b571048dce1f7c60f13580dc8/server/player/player.go#L1403
