### ISSUE TITLE
Keep Inventory

### ISSUE THREAD

**Issue by UramnOIL** [df-mc/dragonfly#684]
I would like to control `dropContent` in Player#kill() when a player dies. I think it is appropriate to add the flag to HandleDeath() like:
```go
func (h *MyHandler) HandleDeath(drop *bool, src world.DamageSource) {}
```

**Comment by Endermanbugzjfc** [comment]
> I would like to control `dropContent` in Player#kill() when a player dies. I think it is appropriate to add the flag to HandleDeath() like:
> 
> ```go
> func (h *MyHandler) HandleDeath(drop *bool, src world.DamageSource) {}
> ```

Would it work if you updated the inventory during this event?

**Comment by Sandertv** [comment]
I think a bool like this would make sense. Would probably put it after the src parameter and call it `keepInventory` or so.

**Comment by UramnOIL** [comment]
> > I would like to control `dropContent` in Player#kill() when a player dies. I think it is appropriate to add the flag to HandleDeath() like:
> > ```go
> > func (h *MyHandler) HandleDeath(drop *bool, src world.DamageSource) {}
> > ```
> 
> Would it work if you updated the inventory during this event?

The inventory change was not a problem. I will push my code soon.

**Comment by UramnOIL** [comment]
> I think a bool like this would make sense. Would probably put it after the src parameter and call it `keepInventory` or so.

Could `keepInventory` be abbreviated to `keepInv` or something?

**Comment by Sandertv** [comment]
Sure, that works.
