### ISSUE TITLE
cmd.Optional doesn't function as expected with enums

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#697]

**Comment by Sandertv** [comment]
Could you show the command you've made?

**Comment by Sandertv** [comment]
I am guessing you should get an error creating the command with this commit: https://github.com/df-mc/dragonfly/commit/c7aca8334da8e23c4286653572fa63d54f4091db. You should make your `cmd.Enum` implementations of the type `string`.
