### ISSUE TITLE
Server crashed when spawning any entities

### ISSUE THREAD

**Issue by ItsZodiaX** [df-mc/dragonfly#710]
This is caused by [Entities EntityRegistry](https://github.com/df-mc/dragonfly/blob/69e0b28484a695785938d62c65f8ef31a01da034/server/world/conf.go#L41) in world's config not being assigned.

**Comment by JustTalDevelops** [comment]
It's set to the default registry if no types are supported by it. More likely I suppose is that you have a custom registry which doesn't properly support the entities that you're trying to spawn.
