### ISSUE TITLE
Absorption effect doesn't get clear client side

### ISSUE THREAD

**Issue by ItsZodiaX** [df-mc/dragonfly#712]
So if someone eats a golden apple which applies the absorption effect.
Whenever [this code](https://github.com/df-mc/dragonfly/blob/066ff5059d65f597ec3f13fff2195f5c27216e92/server/player/player.go#L587) gets fired it only removed the absorption effect from [effects map](https://github.com/df-mc/dragonfly/blob/066ff5059d65f597ec3f13fff2195f5c27216e92/server/entity/effect.go#L14).
When trying to clear effects with [RemoveEffect](https://github.com/df-mc/dragonfly/blob/066ff5059d65f597ec3f13fff2195f5c27216e92/server/player/player.go#L814) that also update the client side, apparently absorption effect doesn't stay in map anymore. So the absorption effect doesn't get clear client side.
```go
for _, eff := range *Player.Effects() {
	*Player.RemoveEffect(eff.Type())
}
```

**Comment by JustTalDevelops** [comment]
I don't think that's the issue - from what I understand, you're trying to remove absorption through RemoveEffect, however the absorption hearts are controlled by an attribute which can be modified by `p.SetAbsorption` and `p.Absorption`. We should probably `SetAbsorption` to zero after removing an absorption effect from a player.

**Comment by JustTalDevelops** [comment]
Fixed with latest commits.
