### ISSUE TITLE
Incorrect Regeneration effect implementation

### ISSUE THREAD

**Issue by ItsZodiaX** [df-mc/dragonfly#713]
[vanilla](https://cdn.discordapp.com/attachments/1040946853388242944/1054353398440394793/2022-12-19_18-00-27.mp4) vs [df](https://cdn.discordapp.com/attachments/1040946853388242944/1054353399937761310/2022-12-19_18-01-42.mp4) (also have normal difficulty)

**Comment by JustTalDevelops** [comment]
Latest commit should fix this.
