### ISSUE TITLE
Implement UpdateQuery

### ISSUE THREAD

**Issue by xKaOz** [df-mc/dragonfly#727]
Not sure how exactly to explain this but, a way to modify the query count of players on the server would be useful, for the people using hubs so they can display count of the full network, as people are less likely to join if it says ‘0/1’

**Comment by xKaOz** [comment]
something like srv().UpdateQuery()

where you can do stuff like SetPlayerCount, SetMotd, ect

**Comment by T14Raptor** [comment]
I think a way to implement custom status providers would be the best solution.

**Comment by didntpot** [comment]
Any updates on this?
