### ISSUE TITLE
Item mismatch on client side when trying to switch an item while consuming something

### ISSUE THREAD

**Issue by ItsZodiaX** [df-mc/dragonfly#730]
[Pov](https://cdn.discordapp.com/attachments/913343096517976104/1062675387311734804/Minecraft_2023.01.11_-_19.08.50.06.DVR-00.00.03.883-00.00.10.415.mp4)
[Another Pov](https://cdn.discordapp.com/attachments/913343096517976104/1062675376280711218/RPReplay_Final1673431732.mov)

This cause the client [can't move](https://cdn.discordapp.com/attachments/913343096517976104/1062670673719341056/Minecraft_2023.01.11_-_18.52.45.03.mp4) that item on inv due to the item not syncing with server-side

**Comment by didntpot** [comment]
Any updates on this?
