### ISSUE TITLE
Crashing when i trying to place some blocks

### ISSUE THREAD

**Issue by VinkyV** [df-mc/dragonfly#763]
# Sign
![image](https://user-images.githubusercontent.com/75137786/236683949-a3966efd-4672-45b2-88ae-e561cc98cbb1.png)
# Skull
![image](https://user-images.githubusercontent.com/75137786/236684578-3ec1855a-5e5e-4382-a2ba-c83fac0645a9.png)
Crashing when i trying place Enchanting Table, Skulls, Sign and other untested.
I'm new in go and doesn't know how to fix it.

Dragonfly version: [e9cf413125](https://github.com/df-mc/dragonfly/tree/e9cf41312599954fc35d15e45b710c45ee626dfd)
Architecture: AMD x64
OS: Windows 10 x64
Client: Minecraft 1.19.81 x64

**Comment by TwistedAsylumMC** [comment]
This was fixed in ab9c2016e285531d8980bd13622af806c105de52. Thanks for reporting
