### ISSUE TITLE
Inventory issue

### ISSUE THREAD

**Issue by xNatsuri** [df-mc/dragonfly#769]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Rewarded-%237E24E3.svg" />](https://oss.issuehunt.io/r/df-mc/dragonfly/issues/769)

Sometimes randomly you are unable to open your inventory, it attempts to open it but never shows the gui.

In the video everytime i stop walking its me trying to open my inventory.

[Video](https://streamable.com/gto2oh)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars.githubusercontent.com/u/86489758?v=4' alt='xnatsuri' width=24 height=24> xnatsuri](https://oss.issuehunt.io/u/xnatsuri) ($20.00)

### Submitted pull Requests
- [#794 Fixed inventories not opening under sub chunk request system](https://oss.issuehunt.io/r/df-mc/dragonfly/pull/794)
---

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/df-mc/dragonfly/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by RestartFU** [comment]
would you have any information about what's causing the issue?

**Comment by Sandertv** [comment]
Does anyone have a world (or approach) that reliably reproduces this that we could test with locally?
