### ISSUE TITLE
Implement custom blocks

### ISSUE THREAD

**Issue by RoyalMCPE** [df-mc/dragonfly#812]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24150%20Funded-%2300A156.svg" />](https://oss.issuehunt.io/r/df-mc/dragonfly/issues/812)

Just need an issue opened for issuehunt

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $150.00)

- [<img src='https://avatars.githubusercontent.com/u/20691625?v=4' alt='royalmcpe' width=24 height=24> royalmcpe](https://oss.issuehunt.io/u/royalmcpe) ($150.00)

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/df-mc/dragonfly/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by TwistedAsylumMC** [comment]
This has been implemented in https://github.com/df-mc/dragonfly/commit/3425d39f7d04d209a4fd97e441ecfe853a24b911. Thank you for funding this issue!
