### ISSUE TITLE
Commands that the player is not supposed to have access to show up

### ISSUE THREAD

**Issue by imlighty** [df-mc/dragonfly#815]
![Image showing the issue](https://github.com/df-mc/dragonfly/assets/45460688/c052b589-7d0b-4947-8ae2-46edfc2643a6)
This issue started after dragonfly got updated to support version `1.20.30`. I don't know if this is a gophertunnel specific issue, but I don't think it is. Commands that have an additional `/` or commands like `mute`, `op` are not supposed to show up to the normal player without operator privileges.

**Comment by Flonja** [comment]
Do you have a simple code example that reproduces this problem?
