### ISSUE TITLE
Got kicked from the server after placing a sign

### ISSUE THREAD

**Issue by lightyisreal** [df-mc/dragonfly#817]
After I placed the sign, I got kicked with the server. An error shows in the logs:
```
DEBU[0093] 2023/10/11 04:31:51 unexpected packet with ID 56  src=gophertunnel
```

**Comment by TwistedAsylumMC** [comment]
This was fixed in https://github.com/Sandertv/gophertunnel/commit/539a193680b2df72ef627cd34fbba01105a358dc
