### ISSUE TITLE
Kicked from the server after punching an item frame

### ISSUE THREAD

**Issue by imlighty** [df-mc/dragonfly#818]
I imported a Bedrock world to dragonfly, punched an item frame to get the item (that had no enchantments, even if it was supposed to have some) and got kicked from the server with this debug message in the console:
```
DEBU[0681] 2023/10/14 04:37:52 unexpected packet with ID 71  src=gophertunnel
```

**Comment by NopeNotDark** [comment]
Yeah so this happens when you punch a item frame, seems like that is what the error is referring to when you got it
