### ISSUE TITLE
Custom Enchants dont save on item drop

### ISSUE THREAD

**Issue by Brougud** [df-mc/dragonfly#862]
When creating a custom enchant, I have ran into the problem of the enchant not working after the item is dropped, there is no errors or anything, the item just simply wont register that there is a custom enchant on there.

I am giving the enchanted item, to the player on the `accept(p *player.Player)` and have tried setting the item's enchants again on pickup, and drop, to no avail.

Here is how I am registering the enchant

```go
enchants := map[int]CustomEnchant{
    100: Explosion{},
}

for id, e := range enchants {
    item.RegisterEnchantment(id, e)
    fmt.Println("Registered Enchant " + e.Name())
}
```

here is how I am giving the item to the player

```go
stack := item.NewStack(item.Pickaxe{Tier: item.ToolTierNetherite}, 1)
stack = stack.WithEnchantments(ce.NewExplosion(3))
stack = stack.WithEnchantments(item.NewEnchantment(enchantment.Efficiency{}, 200))
stack = ce.LoreItem(stack)

pl.Inventory().AddItem(stack)
```

the `NewExplosion()` method

```go
func NewExplosion(lvl int) item.Enchantment {
    return item.NewEnchantment(Explosion{lvl: lvl}, lvl)
}
```

and when I was debugging, I found that this is whats printed for the items `ItemStack.Enchantments()`: `[{{} 200}]`.

Finally, I will reiterate that this enchant **does** work, when the item is first given to the player, however after you drop it and pick it back up, it will not.

**Comment by TwistedAsylumMC** [comment]
Discussed on discord, was the result of OP's implementation of the enchant
