### ISSUE TITLE
Wither effect not causing damage from rose

### ISSUE THREAD

**Issue by RoyalMCPE** [df-mc/dragonfly#944]
While a player is standing on a wither rose they do not take any damage from the withering effect until the player moves off the rose and the effect expires 

https://github.com/user-attachments/assets/18b83d84-60bb-4a3d-9488-b5af97755848

**Comment by Sandertv** [comment]
Issue is (partially) a result of constant re-application of the wither effect, which means that its duration never goes down while standing in the flower. This means you are untouched while staying inside of it.

**Comment by Sandertv** [comment]
Please try the latest commit on the master branch and see if that works as expected.

**Comment by Sandertv** [comment]
Fixed in 3236eac05ccaa667a398b623903547bb58fe10c8.
